### ISSUE TITLE
Segfault in mavsdk_server

### ISSUE THREAD

**Issue by julianoes** [mavlink/MAVSDK#1091]
```
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007f80767d6a46 in std::_Sp_counted_base<(__gnu_cxx::_Lock_policy)2>::_M_release (this=0x7f8038007c20) at /usr/include/c++/9.3.0/bits/shared_ptr_base.h:155
155		    _M_dispose();
[Current thread is 1 (Thread 0x7f803ffff700 (LWP 1939995))]
(gdb) bt
#0  0x00007f80767d6a46 in std::_Sp_counted_base<(__gnu_cxx::_Lock_policy)2>::_M_release (this=0x7f8038007c20) at /usr/include/c++/9.3.0/bits/shared_ptr_base.h:155
#1  0x00007f80767d4769 in std::__shared_count<(__gnu_cxx::_Lock_policy)2>::~__shared_count (this=0x7f803fffe498, __in_chrg=<optimized out>) at /usr/include/c++/9.3.0/bits/shared_ptr_base.h:730
#2  0x00007f80767dcdae in std::__shared_ptr<std::promise<void>, (__gnu_cxx::_Lock_policy)2>::~__shared_ptr (this=0x7f803fffe490, __in_chrg=<optimized out>) at /usr/include/c++/9.3.0/bits/shared_ptr_base.h:1169
#3  0x00007f80767dcdca in std::shared_ptr<std::promise<void> >::~shared_ptr (this=0x7f803fffe490, __in_chrg=<optimized out>) at /usr/include/c++/9.3.0/bits/shared_ptr.h:103
#4  0x00007f80767deae7 in mavsdk::backend::TelemetryServiceImpl<mavsdk::Telemetry>::SubscribeInAir (this=0x55a4434c15b0, writer=0x7f803fffe820) at /home/julianoes/src/MAVSDK/src/backend/src/plugins/telemetry/telemetry_service_impl.h:1116
#5  0x00007f8076bbba85 in std::__invoke_impl<grpc::Status, grpc::Status (mavsdk::rpc::telemetry::TelemetryService::Service::* const&)(grpc_impl::ServerContext*, mavsdk::rpc::telemetry::SubscribeInAirRequest const*, grpc_impl::ServerWriter<mavsdk::rpc::telemetry::InAirResponse>*), mavsdk::rpc::telemetry::TelemetryService::Service*, grpc_impl::ServerContext*, mavsdk::rpc::telemetry::SubscribeInAirRequest const*, grpc_impl::ServerWriter<mavsdk::rpc::telemetry::InAirResponse>*> (
    __f=@0x55a4434bf4c8: &virtual mavsdk::rpc::telemetry::TelemetryService::Service::SubscribeInAir(grpc_impl::ServerContext*, mavsdk::rpc::telemetry::SubscribeInAirRequest const*, grpc_impl::ServerWriter<mavsdk::rpc::telemetry::InAirResponse>*), __t=@0x7f803fffe738: 0x55a4434c15b0)
    at /usr/include/c++/9.3.0/bits/invoke.h:73
#6  0x00007f8076bb6a71 in std::__invoke<grpc::Status (mavsdk::rpc::telemetry::TelemetryService::Service::* const&)(grpc_impl::ServerContext*, mavsdk::rpc::telemetry::SubscribeInAirRequest const*, grpc_impl::ServerWriter<mavsdk::rpc::telemetry::InAirResponse>*), mavsdk::rpc::telemetry::TelemetryService::Service*, grpc_impl::ServerContext*, mavsdk::rpc::telemetry::SubscribeInAirRequest const*, grpc_impl::ServerWriter<mavsdk::rpc::telemetry::InAirResponse>*> (
    __fn=@0x55a4434bf4c8: &virtual mavsdk::rpc::telemetry::TelemetryService::Service::SubscribeInAir(grpc_impl::ServerContext*, mavsdk::rpc::telemetry::SubscribeInAirRequest const*, grpc_impl::ServerWriter<mavsdk::rpc::telemetry::InAirResponse>*)) at /usr/include/c++/9.3.0/bits/invoke.h:96
#7  0x00007f8076babc0f in std::_Mem_fn_base<grpc::Status (mavsdk::rpc::telemetry::TelemetryService::Service::*)(grpc_impl::ServerContext*, mavsdk::rpc::telemetry::SubscribeInAirRequest const*, grpc_impl::ServerWriter<mavsdk::rpc::telemetry::InAirResponse>*), true>::operator()<mavsdk::rpc::telemetry::TelemetryService::Service*, grpc_impl::ServerContext*, mavsdk::rpc::telemetry::SubscribeInAirRequest const*, grpc_impl::ServerWriter<mavsdk::rpc::telemetry::InAirResponse>*> (this=0x55a4434bf4c8) at /usr/include/c++/9.3.0/functional:114
#8  0x00007f8076b99f9e in std::_Function_handler<grpc::Status (mavsdk::rpc::telemetry::TelemetryService::Service*, grpc_impl::ServerContext*, mavsdk::rpc::telemetry::SubscribeInAirRequest const*, grpc_impl::ServerWriter<mavsdk::rpc::telemetry::InAirResponse>*), std::_Mem_fn<grpc::Status (mavsdk::rpc::telemetry::TelemetryService::Service::*)(grpc_impl::ServerContext*, mavsdk::rpc::telemetry::SubscribeInAirRequest const*, grpc_impl::ServerWriter<mavsdk::rpc::telemetry::InAirResponse>*)> >::_M_invoke(std::_Any_data const&, mavsdk::rpc::telemetry::TelemetryService::Service*&&, grpc_impl::ServerContext*&&, mavsdk::rpc::telemetry::SubscribeInAirRequest const*&&, grpc_impl::ServerWriter<mavsdk::rpc::telemetry::InAirResponse>*&&) (__functor=..., __args#0=@0x7f803fffe738: 0x55a4434c15b0, __args#1=@0x7f803fffe730: 0x7f8038003da0, __args#2=@0x7f803fffe728: 0x7f8038003330, __args#3=@0x7f803fffe720: 0x7f803fffe820)
    at /usr/include/c++/9.3.0/bits/std_function.h:286
#9  0x00007f8076c34765 in std::function<grpc::Status (mavsdk::rpc::telemetry::TelemetryService::Service*, grpc_impl::ServerContext*, mavsdk::rpc::telemetry::SubscribeInAirRequest const*, grpc_impl::ServerWriter<mavsdk::rpc::telemetry::InAirResponse>*)>::operator()(mavsdk::rpc::telemetry::TelemetryService::Service*, grpc_impl::ServerContext*, mavsdk::rpc::telemetry::SubscribeInAirRequest const*, grpc_impl::ServerWriter<mavsdk::rpc::telemetry::InAirResponse>*) const (this=0x55a4434bf4c8, __args#0=0x55a4434c15b0, __args#1=0x7f8038003da0, __args#2=0x7f8038003330, __args#3=0x7f803fffe820)
    at /usr/include/c++/9.3.0/bits/std_function.h:688
#10 0x00007f8076bf7cd3 in grpc_impl::internal::ServerStreamingHandler<mavsdk::rpc::telemetry::TelemetryService::Service, mavsdk::rpc::telemetry::SubscribeInAirRequest, mavsdk::rpc::telemetry::InAirResponse>::RunHandler(grpc::internal::MethodHandler::HandlerParameter const&)::{lambda()#1}::operator()() const (
    this=0x55a4434bf4c0) at /home/julianoes/src/MAVSDK/build/default/third_party/install/include/grpcpp/impl/codegen/method_handler_impl.h:194
#11 0x00007f8076c347bc in grpc_impl::internal::CatchingFunctionHandler<grpc_impl::internal::ServerStreamingHandler<mavsdk::rpc::telemetry::TelemetryService::Service, mavsdk::rpc::telemetry::SubscribeInAirRequest, mavsdk::rpc::telemetry::InAirResponse>::RunHandler(grpc::internal::MethodHandler::HandlerParameter const&)::{lambda()#1}>(grpc_impl::internal::ServerStreamingHandler<mavsdk::rpc::telemetry::TelemetryService::Service, mavsdk::rpc::telemetry::SubscribeInAirRequest, mavsdk::rpc::telemetry::InAirResponse>::RunHandler(grpc::internal::MethodHandler::HandlerParameter const&)::{lambda()#1}&&) (handler=...)
    at /home/julianoes/src/MAVSDK/build/default/third_party/install/include/grpcpp/impl/codegen/method_handler_impl.h:48
#12 0x00007f8076bf7db4 in grpc_impl::internal::ServerStreamingHandler<mavsdk::rpc::telemetry::TelemetryService::Service, mavsdk::rpc::telemetry::SubscribeInAirRequest, mavsdk::rpc::telemetry::InAirResponse>::RunHandler (this=0x55a4434bf4c0, param=...)
    at /home/julianoes/src/MAVSDK/build/default/third_party/install/include/grpcpp/impl/codegen/method_handler_impl.h:190
#13 0x00007f8076832778 in grpc_impl::Server::SyncRequest::CallData::ContinueRunAfterInterception (this=0x7f8038003d40) at /home/julianoes/src/MAVSDK/build/default/third_party/grpc/grpc/src/grpc/src/cpp/server/server_cc.cc:502
#14 0x00007f8076832593 in grpc_impl::Server::SyncRequest::CallData::Run (this=0x7f8038003d40, global_callbacks=std::shared_ptr<grpc_impl::Server::GlobalCallbacks> (use count 11, weak count 0) = {...}, resources=true)
    at /home/julianoes/src/MAVSDK/build/default/third_party/grpc/grpc/src/grpc/src/cpp/server/server_cc.cc:489
#15 0x00007f8076832cf5 in grpc_impl::Server::SyncRequestThreadManager::DoWork (this=0x55a4434f24f0, tag=0x55a4434f7db0, ok=true, resources=true) at /home/julianoes/src/MAVSDK/build/default/third_party/grpc/grpc/src/grpc/src/cpp/server/server_cc.cc:900
#16 0x00007f807684dabb in grpc::ThreadManager::MainWorkLoop (this=0x55a4434f24f0) at /home/julianoes/src/MAVSDK/build/default/third_party/grpc/grpc/src/grpc/src/cpp/thread_manager/thread_manager.cc:211
#17 0x00007f807684d011 in grpc::ThreadManager::WorkerThread::Run (this=0x7f801c004740) at /home/julianoes/src/MAVSDK/build/default/third_party/grpc/grpc/src/grpc/src/cpp/thread_manager/thread_manager.cc:43
#18 0x00007f807684ceac in grpc::ThreadManager::WorkerThread::<lambda(void*)>::operator()(void *) const (__closure=0x0, th=0x7f801c004740) at /home/julianoes/src/MAVSDK/build/default/third_party/grpc/grpc/src/grpc/src/cpp/thread_manager/thread_manager.cc:35
#19 0x00007f807684cecc in grpc::ThreadManager::WorkerThread::<lambda(void*)>::_FUN(void *) () at /home/julianoes/src/MAVSDK/build/default/third_party/grpc/grpc/src/grpc/src/cpp/thread_manager/thread_manager.cc:35
#20 0x00007f807715fd47 in grpc_core::(anonymous namespace)::ThreadInternalsPosix::<lambda(void*)>::operator()(void *) const (__closure=0x0, v=0x7f802c005520) at /home/julianoes/src/MAVSDK/build/default/third_party/grpc/grpc/src/grpc/src/core/lib/gprpp/thd_posix.cc:140
#21 0x00007f807715fd91 in grpc_core::(anonymous namespace)::ThreadInternalsPosix::<lambda(void*)>::_FUN(void *) () at /home/julianoes/src/MAVSDK/build/default/third_party/grpc/grpc/src/grpc/src/core/lib/gprpp/thd_posix.cc:145
#22 0x00007f8074b7646f in start_thread () from /usr/lib/libpthread.so.0
#23 0x00007f807501b3d3 in clone () from /usr/lib/libc.so.6
```

This often happens when `python3 examples/telemetry_takeoff_and_land.py` is used.

**Comment by julianoes** [comment]
And this one looks similar:
```
==185243== Invalid read of size 4
==185243==    at 0x6E61050: __pthread_mutex_unlock_full (in /usr/lib/libpthread-2.31.so)
==185243==    by 0x666EF1: __gthread_mutex_unlock(pthread_mutex_t*) (gthr-default.h:779)
==185243==    by 0x667399: std::mutex::unlock() (std_mutex.h:118)
==185243==    by 0x671D3A: std::lock_guard<std::mutex>::~lock_guard() (std_mutex.h:165)
==185243==    by 0x6A9B22: mavsdk::backend::CameraServiceImpl<testing::NiceMock<mavsdk::testing::MockCamera> >::SubscribeVideoStreamInfo(grpc_impl::ServerContext*, mavsdk::rpc::camera::SubscribeVideoStreamInfoRequest const*, grpc_impl::ServerWriter<mavsdk::rpc::camera::VideoStreamInfoResponse>*)::{lambda(mavsdk::Camera::VideoStreamInfo)#1}::operator()(mavsdk::Camera::VideoStreamInfo) const (camera_service_impl.h:758)
==185243==    by 0x6B9D6F: std::_Function_handler<void (mavsdk::Camera::VideoStreamInfo), mavsdk::backend::CameraServiceImpl<testing::NiceMock<mavsdk::testing::MockCamera> >::SubscribeVideoStreamInfo(grpc_impl::ServerContext*, mavsdk::rpc::camera::SubscribeVideoStreamInfoRequest const*, grpc_impl::ServerWriter<mavsdk::rpc::camera::VideoStreamInfoResponse>*)::{lambda(mavsdk::Camera::VideoStreamInfo)#1}>::_M_invoke(std::_Any_data const&, mavsdk::Camera::VideoStreamInfo&&) (std_function.h:300)
==185243==    by 0x67903A: std::function<void (mavsdk::Camera::VideoStreamInfo)>::operator()(mavsdk::Camera::VideoStreamInfo) const (std_function.h:688)
==185243==    by 0x646935: (anonymous namespace)::CameraServiceImplTest::checkSendsVideoStreamInfo(std::vector<mavsdk::Camera::VideoStreamInfo, std::allocator<mavsdk::Camera::VideoStreamInfo> > const&) const (camera_service_impl_test.cpp:535)
==185243==    by 0x6465AF: (anonymous namespace)::CameraServiceImplTest_sendsOneVideoStreamInfo_Test::TestBody() (camera_service_impl_test.cpp:511)
==185243==    by 0x6F8A94C: void testing::internal::HandleSehExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) (gtest.cc:2593)
==185243==    by 0x6F83212: void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) (gtest.cc:2629)
==185243==    by 0x6F5DFD1: testing::Test::Run() (gtest.cc:2668)
==185243==  Address 0x9cdb520 is on thread 5's stack
==185243==  592 bytes below stack pointer
==185243== 
```
