### ISSUE TITLE
[mavsdk-python SITL] mavsdk-server crashes when reading EulerAngle

### ISSUE THREAD

**Issue by norisg** [mavlink/MAVSDK#1334]
I am using mavsdk-python to control my drone in offboard mode. I had problems when trying to use the EulerAngle and reading them in a cycle around 20 Hz.  After some seconds the mavsdk-server will crash. First I thought it was a problem with the use of global variables in python, but after commenting out the lines which read the EulerAngle, it runs perfectly.

**To Reproduce**
1. Switch on SITL(PX4)

2. Start my python program (fcc_bug.py)
3. Start a Testmessage Script which sends messages to the fcc.py

**Comment by norisg** [comment]
`#!/usr/bin/env python3
import math
import socket
import time
from gpiozero import LED
from os import path
import sys
import serial



import asyncio
from mavsdk import System
from mavsdk.action import ActionError
from mavsdk.telemetry import LandedState,PositionNed,FlightMode
from mavsdk.offboard import (OffboardError, PositionNedYaw, VelocityNedYaw)


#========================================#
#==========Constant Variables============#

# Settings
g_c_maxVV           = 3.0
g_c_minHeight       = 2
g_c_maxHAG          = 115
g_c_tolDTG          = 0.3
g_c_tolAlt          = 0.3
g_c_voltage_0m      = 13.8
g_c_voltage_100m    = 15.8
g_c_maxRadius       = 100
g_c_telemBAUD       = 921600
g_c_telemBAUD       = 57600
g_c_clapOn_s        = 0.5
g_c_clapOff_s       = 0.15
g_c_maxTFHaboveMinH = 0.5
g_c_groundSpeed     = 10





async def run():

    global REQ_FM0_LAND
    global REQ_FM1_HOVER
    global REQ_FM2_RETURN_TO_BASE
    global REQ_FM3_USE_COORDINATES
    global REQ_FM4_START
    global REQ_FM3_ALTITUDE_m
    global REQ_FM3_HEADING_deg
    global REQ_FM3_GEO_m
    global REQ_FM3_GROUND_VELOCITY_mps


    global g_isRPI
    global g_startPoint
    global g_beats
    global g_isInitializationPending
    global g_opTheaterRadius
    global g_tfMode
    global g_connectionSuccess
    global g_velocityMode
    #Definition of Variables:


    #Coordinates are relativ to EKF Origin (THIS IS NOT HOME!!!)
    g_isRPI                     = False
    g_startPoint                = [0, 0, 0, 'New Startpoint']
    g_beats                     = []
    g_isInitializationPending   = True
    g_opTheaterRadius           = 100
    g_tfMode                    = False
    g_connectionSuccess         = False
    g_velocityMode              = False
    #FlightModes:
    REQ_FM0_LAND            = False
    REQ_FM1_HOVER           = False
    REQ_FM2_RETURN_TO_BASE  = False
    REQ_FM3_USE_COORDINATES = False
    REQ_FM4_START           = False
    IS_FM0_LAND             = False
    IS_FM1_HOVER            = False
    IS_FM2_RETURN_TO_BASE   = False
    IS_FM3_USE_COORDINATES  = False
    IS_FM4_START            = False

    # Coordinates
    REQ_FM3_ALTITUDE_m          = 0
    REQ_FM3_HEADING_deg         = 0
    REQ_FM3_GEO_m               = [0, 0]
    REQ_FM3_GROUND_VELOCITY_mps = 0

    IS_FM3_ALTITUDE_m           = 0
    IS_FM3_HEADING_deg          = 0
    IS_FM3_GEO_m                = [0,0]
    IS_FM3_GROUND_VELOCITY_mps  = 0



    # Logging
    def log(text = ''):
        with open('log_fcc.txt', 'a') as file:
            file.write('[main]:{}\n'.format(text))

    def display(text = ''):
        print ('[main]:{}\n'.format(text))
        log(text)



    #Starting RX Server:

    streamRX = socket.socket(family=socket.AF_INET, type=socket.SOCK_DGRAM)
    streamRX.bind(('127.0.0.1',8888));
    streamRX.settimeout(0.01)
    #Connecting to Tx Server
    streamTX  = socket.socket(family=socket.AF_INET, type=socket.SOCK_DGRAM)
    addressPortTX = ('127.0.0.1', 8999)
    streamTX.settimeout(0.01)





    hostName = socket.gethostname()
    display('Connecting {} and SITL'.format(hostName))
    # connection_string = '192.168.178.11:14550'  # ICU Pathfinder
    connection_string = 'udp://:14540'



    ################Connecting Drone ###################################
    drone = System() #mavsdk_server is integrated in this command
    #The Following line has to be used if mavsdk_server is started separately for debugging
    #drone = System(mavsdk_server_address='localhost', port=57000)
    await drone.connect(system_address=connection_string)

    display('Waiting for drone to connect...')
    async for state in drone.core.connection_state():
        display(state)
        if state.is_connected:
            display('Drone discovered with UUID: {}'.format(state.uuid))
            g_connectionSuccess = True
            break


    async def udp_server_rx():

       message = ''

       text = ''

       global REQ_FM0_LAND
       global REQ_FM1_HOVER
       global REQ_FM2_RETURN_TO_BASE
       global REQ_FM3_USE_COORDINATES
       global REQ_FM4_START
       global REQ_FM3_ALTITUDE_m
       global REQ_FM3_HEADING_deg
       global REQ_FM3_GEO_m
       global REQ_FM3_GROUND_VELOCITY_mps

       REQ_FM3_GEO_m = [0,0]

       try:

                data, remote_addr = streamRX.recvfrom(1024)

       except socket.timeout as e:
                err = e.args[0]
                # this next if/else is a bit redundant, but illustrates how the
                # timeout exception is setup
                if err == 'timed out':
                    #display ('recv timed out, retry later')
                    return [message, text]
                else:
                    display(e)
                    sys.exit(1)
       except socket.error as e:
            # Something else happened, handle error, exit, etc.
                display(e)
                sys.exit(1)
       else:

               data = list(str(data).replace('b', '').replace('\'', '').split(','))
               REQ_FM0_LAND                = data[0] == 'True' or data[0] == '1'
               REQ_FM1_HOVER               = data[1] == 'True' or data[1] == '1'
               REQ_FM2_RETURN_TO_BASE      = data[2] == 'True' or data[2] == '1'
               REQ_FM3_USE_COORDINATES     = data[3] == 'True' or data[3] == '1'
               REQ_FM4_START               = data[4] == 'True' or data[4] == '1'
               REQ_FM3_ALTITUDE_m          = float(data[5])
               REQ_FM3_HEADING_deg         = float(data[6])
               REQ_FM3_GEO_m[0]            = float(data[7])
               REQ_FM3_GEO_m[1]            = float(data[8])
               REQ_FM3_GROUND_VELOCITY_mps = float(data[9])
               text                        = data[10]



               message = str(data)
               return [message,text]


    async def udp_server_tx(text = ''):

        message = ''

        message = '{},{},{},{},{},{},{},{},{},{},{}'.format(
            IS_FM0_LAND,
            IS_FM1_HOVER,
            IS_FM2_RETURN_TO_BASE,
            IS_FM3_USE_COORDINATES,
            IS_FM4_START,
            '%.2f' % IS_FM3_ALTITUDE_m,
            '%.2f' % IS_FM3_HEADING_deg,
            '%.2f' % IS_FM3_GEO_m[0],
            '%.2f' % IS_FM3_GEO_m[1],
            '%.2f' % IS_FM3_GROUND_VELOCITY_mps,
            text
        ).replace('True', '1').replace('False', '0')


        try:
            streamTX.sendto(message.encode(), addressPortTX)
        except socket.timeout as e:
            err = e.args[0]
           # this next if/else is a bit redundant, but illustrates how the
           # timeout exception is setup
            if err == 'timed out':
                display ('sendingto timed out, retry later')
                return
            else:
                display(e)
                sys.exit(1)
        except socket.error as e:
              # Something else happened, handle error, exit, etc.
                display(e)
                sys.exit(1)
        else:
            return



    # Mission
    display('\n####################################################')
    display('Mission Start')

    message = ''
    lastMessage = ''
    isNewCommand = False
    text = ''
    #########SETTINGS FOR MAVSDK###############################
    #defining Monitoring Rates in Hz:
    await drone.telemetry.set_rate_position_velocity_ned(50)
    await drone.telemetry.set_rate_battery(50)
    await drone.telemetry.set_rate_in_air(50)
    try:
        await drone.action.set_maximum_speed(g_c_groundSpeed)
    except ActionError as error:
        display('Set Max Speed failed with error code: {}'.format(error._result.result))
        return


    while True:
       try:

             ###########Udp SERVER###########

            #start = time.time()
            message, text  = await udp_server_rx()
            #end = time.time()
            #display('udp_server_rx Process Time: {} ms'.format((end - start)*1000))
            if message != lastMessage and message != '':

               lastMessage  = message
               isNewCommand = True
               display(' Received: {}'.format(message))

            async for vehicle in drone.telemetry.position_velocity_ned():

                IS_FM3_ALTITUDE_m  = -vehicle.position.down_m
                IS_FM3_GEO_m[0]   =  vehicle.position.north_m
                IS_FM3_GEO_m[1]    =  vehicle.position.east_m
                IS_FM3_GROUND_VELOCITY_mps = math.sqrt(vehicle.velocity.north_m_s**2 + vehicle.velocity.east_m_s**2)
                break

            async for vehicle in drone.telemetry.attitude_euler():

                heading = vehicle.yaw_deg
                print("Heading: {}".format(heading))
                break





            if REQ_FM0_LAND:
                if isNewCommand:
                    display('\n# LANDING')
                    #await land()
                    #await asyncio.sleep(1)
                    #await disarm()
                IS_FM0_LAND            = True
                IS_FM1_HOVER           = False
                IS_FM2_RETURN_TO_BASE  = False
                IS_FM3_USE_COORDINATES = False
                IS_FM4_START           = False
            elif REQ_FM1_HOVER:
                if isNewCommand:
                    display('\n# HOVERING')
                    #await loiter()
                IS_FM0_LAND            = False
                IS_FM1_HOVER           = True
                IS_FM2_RETURN_TO_BASE  = False
                IS_FM3_USE_COORDINATES = False
                IS_FM4_START           = True
            elif REQ_FM2_RETURN_TO_BASE:
                if isNewCommand:
                    display('\n# RETURNING TO BASE')
                    #await gotoPositionControlled(0, 0, g_c_minHeight,REQ_FM3_HEADING_deg)
                IS_FM0_LAND            = False
                IS_FM1_HOVER           = False
                IS_FM2_RETURN_TO_BASE  = True
                IS_FM3_USE_COORDINATES = False
                IS_FM4_START           = True
            elif REQ_FM3_USE_COORDINATES:
                if isNewCommand:
                    display('\n# FLYING TO POSITION [{}, {}, {}]'.format(REQ_FM3_GEO_m[0], REQ_FM3_GEO_m[1], REQ_FM3_ALTITUDE_m))
                    if REQ_FM3_GROUND_VELOCITY_mps > 0:
                        try:
                            await drone.action.set_maximum_speed(REQ_FM3_GROUND_VELOCITY_mps)
                        except ActionError as error:
                            display('Set Max Speed failed with error code: {}'.format(error._result.result))
                            return
                    display('COMMAND#:gotoPosition')
                    #await gotoPositionControlled(REQ_FM3_GEO_m[0], REQ_FM3_GEO_m[1], REQ_FM3_ALTITUDE_m,REQ_FM3_HEADING_deg)
                IS_FM0_LAND            = False
                IS_FM1_HOVER           = False
                IS_FM2_RETURN_TO_BASE  = False
                IS_FM3_USE_COORDINATES = True
                IS_FM4_START           = True
            elif REQ_FM4_START:
                if isNewCommand:
                    async for arm_state in drone.telemetry.armed():
                        if not arm_state:
                            display("arm_state: {}".format(arm_state))
                            display('\n# STARTING ROTORS')
                            #await arm()
                        break
                IS_FM0_LAND            = False
                IS_FM1_HOVER           = False
                IS_FM2_RETURN_TO_BASE  = False
                IS_FM3_USE_COORDINATES = False
                IS_FM4_START           = True


            #start = time.time()
            await udp_server_tx(text)
            #end = time.time()
            #display('udp_server_tx Process Time: {} ms'.format((end - start)*1000))


            REQ_FM0_LAND            = False
            REQ_FM1_HOVER           = False
            REQ_FM2_RETURN_TO_BASE  = False
            REQ_FM3_USE_COORDINATES = False
            REQ_FM4_START           = False
            isNewCommand            = False

            await asyncio.sleep(0.1)
            #end = time.time()
            #display('Drone Task Process Time: {} ms'.format((end - start)*1000))

       except Exception as e:
             display(e)
             display("=============================")
             display("Error proceed with Emergency Land")
             display("=============================")
             await land(drone)
             streamRX.close()



if __name__ == "__main__":
    try:
        loop = asyncio.get_event_loop()
        loop.run_until_complete(run())

    except KeyboardInterrupt:
        print("Programm aborted, please start again")
`

**Comment by norisg** [comment]
The Following is the testmessage.py program which sends dummy data to the fcc.py:

```
import socket
import time


# Communication
# Create a UDP socket
streamTX = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
addressPortTX = ('localhost', 8888)

streamRX = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)

streamRX.bind(('127.0.0.1',8999))

# terminal A
streamRX.setsockopt(socket.SOL_SOCKET, socket.SO_RCVBUF, 512)
# Prints "1024":
print(streamRX.getsockopt(socket.SOL_SOCKET, socket.SO_RCVBUF))
```
```

# Flight Modes
REQ_FM0_LAND            = False
REQ_FM1_HOVER           = False
REQ_FM2_RETURN_TO_BASE  = False
REQ_FM3_USE_COORDINATES = False
REQ_FM4_START           = False
REQ_MESSAGE             = ''

IS_FM0_LAND            = False
IS_FM1_HOVER           = False
IS_FM2_RETURN_TO_BASE  = False
IS_FM3_USE_COORDINATES = False
IS_FM4_START           = False

# Coordinates
REQ_FM3_ALTITUDE_m          = 0
REQ_FM3_HEADING_deg         = 0
REQ_FM3_GEO_m               = [0, 0]
REQ_FM3_GROUND_VELOCITY_mps = 0

IS_FM3_ALTITUDE_m          = 0
IS_FM3_HEADING_deg         = 0
IS_FM3_GEO_m               = [0, 0]
IS_FM3_GROUND_VELOCITY_mps = 0


def SetReq(data):
    global REQ_FM0_LAND
    global REQ_FM1_HOVER
    global REQ_FM2_RETURN_TO_BASE
    global REQ_FM3_USE_COORDINATES
    global REQ_FM4_START
    global REQ_FM3_ALTITUDE_m
    global REQ_FM3_HEADING_deg
    global REQ_FM3_GEO_m
    global REQ_FM3_GROUND_VELOCITY_mps

    REQ_FM0_LAND                = data[0]
    REQ_FM1_HOVER               = data[1]
    REQ_FM2_RETURN_TO_BASE      = data[2]
    REQ_FM3_USE_COORDINATES     = data[3]
    REQ_FM4_START               = data[4]
    REQ_FM3_ALTITUDE_m          = data[5]
    REQ_FM3_HEADING_deg         = data[6]
    REQ_FM3_GEO_m               = [data[7], data[8]]
    REQ_FM3_GROUND_VELOCITY_mps = data[9]


def _send(message = ''):
    message = '{},{},{},{},{},{},{},{},{},{},{}'.format(
        REQ_FM0_LAND,
        REQ_FM1_HOVER,
        REQ_FM2_RETURN_TO_BASE,
        REQ_FM3_USE_COORDINATES,
        REQ_FM4_START,
        REQ_FM3_ALTITUDE_m,
        REQ_FM3_HEADING_deg,
        REQ_FM3_GEO_m[0],
        REQ_FM3_GEO_m[1],
        REQ_FM3_GROUND_VELOCITY_mps,
        message
    ).encode()
    streamTX.sendto(message, addressPortTX)


def _receive():
    global IS_FM0_LAND
    global IS_FM1_HOVER
    global IS_FM2_RETURN_TO_BASE
    global IS_FM3_USE_COORDINATES
    global IS_FM4_START
    global IS_FM3_ALTITUDE_m
    global IS_FM3_HEADING_deg
    global IS_FM3_GEO_m
    global IS_FM3_GROUND_VELOCITY_mps

    data, remote_addr = streamRX.recvfrom(1024)
    data = list(str(data).replace('b', '').replace('\'', '').split(','))
    IS_FM0_LAND                = data[0] == 'True' or data[0] == '1'
    IS_FM1_HOVER               = data[1] == 'True' or data[1] == '1'
    IS_FM2_RETURN_TO_BASE      = data[2] == 'True' or data[2] == '1'
    IS_FM3_USE_COORDINATES     = data[3] == 'True' or data[3] == '1'
    IS_FM4_START               = data[4] == 'True' or data[4] == '1'
    IS_FM3_ALTITUDE_m          = float(data[5])
    IS_FM3_HEADING_deg         = float(data[6])
    IS_FM3_GEO_m[0]            = float(data[7])
    IS_FM3_GEO_m[1]            = float(data[8])
    IS_FM3_GROUND_VELOCITY_mps = float(data[9])
    print('Receiving: {}'.format(data))


```
```

def main():

    timeStart = time.time()
    timeElapsed = 0
    defaultTimeIncrement = 10
    timeLastStamp = 30
    timeStamps = []
    reqs = []

    print(' 0: Land')
    print(' 1: Hover')
    print(' 2: RTB')
    print(' 3: Coords')
    print(' 4: Start')
    print(' 5: Altitude')
    print(' 6: Heading')
    print(' 7: North')
    print(' 8: East')
    print(' 9: Velocity')
    print('10: Message\n')

#    takeInput()
    #for i in range(1<<8):
    #    timeStamps.append(10 * i)

    #reqsCount = 0
    #for land in range(2):
    #    for hover in range(2):
    #        for rtb in range(2):
    #            for useCoords in range(2):
    #                for start in range(2):
    #                    for alt in range(2):
    #                        for head in range(2):
    #                            for goNE in range(2):
    #                                reqs.append([land, hover, rtb, useCoords, start, alt * 10, head * -120, goNE * 150, goNE * 100, 5])
    #                                reqsCount = reqsCount + 1





    reqsCount = 8
    reqs = [
        # Land
        # |  Hover
        # |  |  RTB
        # |  |  |  Coords
        # |  |  |  |  Start
        # |  |  |  |  |  Altitude
        # |  |  |  |  |  |   Heading
        # |  |  |  |  |  |   |   North East Velocity
        # |  |  |  |  |  |   |   |     |    |
        [ 0, 0, 0, 0, 1,  0, 0,    0,    0, 5, 'Start'],
        [ 0, 0, 0, 1, 0, 20, 0,  100,  100, 5, 'Move to Alt 20m, 100m north, 100m east'],
        [ 0, 0, 0, 1, 0, 20, 0, -100,  100, 5, 'Move to Alt 20m, 100m south, 100m east'],
        [ 0, 0, 0, 1, 0, 20, 0, -100, -100, 5, 'Move to Alt 20m, 100m south, 100m west'],
        [ 0, 0, 0, 1, 0, 20, 0,  100, -100, 5, 'Move to Alt 20m, 100m north, 100m west'],
        [ 0, 0, 1, 0, 0, 20, 0,  100,  300, 5, 'RTB'],
        [ 0, 1, 0, 0, 0, 20, 0,  100,  300, 5, 'Hover'],
        [ 1, 0, 0, 0, 0,  0, 0,  100,  300, 5, 'Land'],
    ]
    timeStamps = [10, 30, 90, 120, 150]

    # Fixing timeStamps, append 10s intervals if necessary
    if len(timeStamps) == 0:
        timeStamps.append(0)
    while len(timeStamps) < len(reqs):
        timeStamps.append(timeStamps[-1] + defaultTimeIncrement)
    print(timeStamps)

    # Continuously sending Data according to timeStamps
    while timeElapsed < timeStamps[len(timeStamps) - 1] + timeLastStamp:
        index = -1
        for i, item in enumerate(timeStamps):
            if timeElapsed >= timeStamps[i] and index + 1 < len(reqs):
                index = index + 1
        if index >= 0:
            req = reqs[index]
            SetReq(req)
            print("Send")
            _send(req[-1])
            print("Receive")
            _receive()
        timeElapsed = time.time() - timeStart
        time.sleep(1)


if __name__ == '__main__':
    main()

```

**Comment by norisg** [comment]
This is the Error Log I am getting:


> Waiting for mavsdk_server to be ready...
> Connected to mavsdk_server!
> [main]:Waiting for drone to connect...
> 
> [main]:ConnectionState: [uuid: 0, is_connected: True]
> 
> [main]:Drone discovered with UUID: 0
> 
> [main]:
> ####################################################
> 
> [main]:Mission Start
> 
> Heading: -2.4270238876342773
> Heading: -2.485532522201538
> Heading: -2.582531690597534
> Heading: -2.64835524559021
> Heading: -2.6578786373138428
> Heading: -2.647286891937256
> Heading: -2.6339972019195557
> __anext__ grpc exception
> Traceback (most recent call last):
>   File "///.virtualenvs/mavsdk-python/lib/python3.8/site-packages/aiogrpc/utils.py", line 145, in cb
>     fut.result()
>   File "/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/concurrent/futures/thread.py", line 57, in run
>     result = self.fn(*self.args, **self.kwargs)
>   File "///.virtualenvs/mavsdk-python/lib/python3.8/site-packages/aiogrpc/utils.py", line 131, in _next
>     return next(self._iterator)
>   File "///.virtualenvs/mavsdk-python/lib/python3.8/site-packages/grpc/_channel.py", line 416, in __next__
>     return self._next()
>   File "///.virtualenvs/mavsdk-python/lib/python3.8/site-packages/grpc/_channel.py", line 786, in _next
>     raise self
> grpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:
>     status = StatusCode.UNAVAILABLE
>     details = "Connection reset by peer"
>     debug_error_string = "{"created":"@1614542611.595399000","description":"Error received from peer ipv6:[::1]:50051","file":"src/core/lib/surface/call.cc","file_line":1068,"grpc_message":"Connection reset by peer","grpc_status":14}"
> >
> [main]:<_MultiThreadedRendezvous of RPC that terminated with:
>     status = StatusCode.UNAVAILABLE
>     details = "Connection reset by peer"
>     debug_error_string = "{"created":"@1614542611.595399000","description":"Error received from peer ipv6:[::1]:50051","file":"src/core/lib/surface/call.cc","file_line":1068,"grpc_message":"Connection reset by peer","grpc_status":14}"
> >
>

**Comment by julianoes** [comment]
@norisg thanks for the issue. What is your mavsdk version from PyPi and which what mavsdk_server version are you using? My suspicion is that something is not matching.

**Comment by norisg** [comment]
@julianoes I am using (mavsdk 0.15.0) in the mavsdk and mavsdk_server (v0.36.0-2-g6f71cc15) but it crashes in both ways. When I start mavsdk in the python program with ` drone = System() #mavsdk_server is integrated in this command` or when I run mavsdk_server separately with the command ` #drone = System(mavsdk_server_address='localhost', port=57000)` So one might think that when I start mavsdk server in python it should work

**Comment by julianoes** [comment]
@norisg We just released 0.17.0. Could you check if it is fixed now? Otherwise I should look into this.
